server:
  port: 8080

spring:
  data:
    mongodb:
      database: orderdb
      authentication-database: admin
      host: localhost
      password:
      port: 27017
      username:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: smartpayment-orders
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: ${spring.kafka.properties.schema.registry.url}
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schema.registry.url: ${spring.kafka.properties.schema.registry.url}
  sleuth:
    opentracing:
      enabled: true
    sampler:
      probability: 1.0
    trace-id128: true

topic:
  input:
    order-requested: order-requested
    order-validated: order-validated
  output:
    order-status-updated: order-status-updated


endpoint:
  orders:
    url: http://localhost:8081/orders